language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.4
script: bundle exec rspec
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0-p648
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
